(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/xia-editor/xia-editor"],{"064f":function(t,e,n){"use strict";n.r(e);var i=n("7bc9"),o=n("60c1");for(var r in o)["default"].indexOf(r)<0&&function(t){n.d(e,t,(function(){return o[t]}))}(r);n("dfe5");var c,a=n("7702"),u=Object(a["a"])(o["default"],i["b"],i["c"],!1,null,null,null,!1,i["a"],c);e["default"]=u.exports},"4c6d":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;e.default={props:{value:{type:String,default:""},placeholder:{type:String,default:"开始输入..."}},data:function(){return{readOnly:!1,formats:{}}},model:{prop:"value",event:"change"},methods:{shibieText:function(e){var n=this;t.createSelectorQuery().select("#editor").context((function(t){n.editorCtx=t.context,n.editorCtx.setContents({html:e})})).exec()},editText:function(t){this.$emit("editorChange",t.detail.html)},readOnlyChange:function(){this.readOnly=!this.readOnly},onEditorReady:function(){var e=this,n=t.createSelectorQuery().in(this);n.select("#editor").context((function(t){t&&null!=t&&(e.editorCtx=t.context,e.editorCtx.setContents({html:e.value}))})).exec()},undo:function(){this.editorCtx.undo()},redo:function(){this.editorCtx.redo()},format:function(t){var e=t.target.dataset,n=e.name,i=e.value;n&&this.editorCtx.format(n,i)},onStatusChange:function(t){var e=t.detail;this.formats=e},insertDivider:function(){this.editorCtx.insertDivider({success:function(){console.log("insert divider success")}})},clear:function(){this.editorCtx.clear({success:function(t){console.log("clear success")}})},removeFormat:function(){this.editorCtx.removeFormat()},insertDate:function(){var t=new Date,e="".concat(t.getFullYear(),"/").concat(t.getMonth()+1,"/").concat(t.getDate());this.editorCtx.insertText({text:e})},insertImage:function(){var t=this;t.$api.upload((function(e){t.editorCtx.insertImage({src:t.$base.url+"upload/"+e.file,alt:"图像",success:function(){console.log("insert image success")}})}))}},onLoad:function(){t.loadFontFace({family:"Pacifico",source:'url("./Pacifico.ttf")'})}}}).call(this,n("255a")["default"])},"52bb":function(t,e,n){},"60c1":function(t,e,n){"use strict";n.r(e);var i=n("4c6d"),o=n.n(i);for(var r in i)["default"].indexOf(r)<0&&function(t){n.d(e,t,(function(){return i[t]}))}(r);e["default"]=o.a},"7bc9":function(t,e,n){"use strict";var i;n.d(e,"b",(function(){return o})),n.d(e,"c",(function(){return r})),n.d(e,"a",(function(){return i}));var o=function(){var t=this,e=t.$createElement;t._self._c},r=[]},dfe5:function(t,e,n){"use strict";var i=n("52bb"),o=n.n(i);o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/xia-editor/xia-editor-create-component',
    {
        'components/xia-editor/xia-editor-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('255a')['createComponent'](__webpack_require__("064f"))
        })
    },
    [['components/xia-editor/xia-editor-create-component']]
]);
